version: '3'

services:
    client:
        build:
            context: ./
            dockerfile: ./client/Dockerfile
            args: 
                DIR_APP: ./client
        image: client_socket
        container_name: cli
        restart: always
        ports:
           - '4003:3000'
#        links:
#            - "server"
        depends_on:
          - "server"
        networks:
          - net

    server:
        container_name: server
        image: server_socket
        ports:
            - '4002:4001'
        build: 
            dockerfile: ./server/Dockerfile
            context: ./
            args: 
                DIR_APP: ./server
        restart: always
        networks: 
            - net

networks:
  net:
    driver: bridge

